<html>
<head>
<meta charset="utf-8">
</head>

<body>

<h1>
File Show/Download Demo!
</h1>

<p>
    File will be displayed inline in the browser: <a href="<?=cg\html\request_url('File/Show')?>">Display file!</a>
</p>

<img src="<?=cg\html\request_url('File/Show')?>" />

<p>
File will be downloaded and saved locally: <a href="<?=cg\html\request_url('File/Download')?>">Download file!</a>
</p>

<img src="<?=cg\html\request_url('File/Download')?>" />

</body>
</html>